In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import OneHotEncoder

train = pd.read_csv("train_beats.csv", header=None)
test = pd.read_csv("test_beats.csv", header=None)

X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values.astype(int)

X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values.astype(int)

print("Train:", X_train.shape, " Test:", X_test.shape)


svm = SVC(kernel='rbf', class_weight='balanced')
svm.fit(X_train, y_train)


y_pred = svm.predict(X_test)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average='macro')
rec = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1 score:", f1)
print("Confusion matrix:\n", cm)


Train: (30992, 276)  Test: (37442, 276)
Accuracy: 0.9538219112226911
Precision: 0.9469641958585576
Recall: 0.9465668645914079
F1 score: 0.9414705597628011
Confusion matrix:
 [[1155    0    0 ...    0    0    1]
 [   0  807    0 ...    0    0    0]
 [   0    0  530 ...    0    1    0]
 ...
 [   0    0    0 ...  447    0    0]
 [   0    0    0 ...    0  708    0]
 [   1    0    0 ...    0    0 1327]]


In [2]:
train = pd.read_csv("train_patients.csv", header=None)
test = pd.read_csv("test_patients.csv", header=None)

X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values.astype(int)

X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values.astype(int)

print("Train:", X_train.shape, " Test:", X_test.shape)


svm_patient = SVC(kernel='rbf', class_weight='balanced')
svm_patient.fit(X_train, y_train)


y_pred = svm_patient.predict(X_test)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average='macro')
rec = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1 score:", f1)
print("Confusion matrix:\n", cm)


Train: (200352, 276)  Test: (14482, 276)
Accuracy: 0.9487639828752935
Precision: 0.12421491512696373
Recall: 0.11886686493377144
F1 score: 0.1213808294937653
Confusion matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


c:\Users\AlexCheng\.conda\envs\idss\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
